### ISSUE TITLE
Usabilità burger menu

### ISSUE THREAD

**Issue by gunzip** [italia/designer.italia.it#162]
> Discussioni sull'usabilità di questa soluzione attualmente molto controversa

L'argomento è stato sviscerato [in italia](http://www.usabile.it/632016-icona-hamburger-dannosa) e [nel mondo](https://www.nngroup.com/articles/hamburger-menus/). Nei [commenti sull'articolo di usabile.it](http://www.usabile.it/632016-icona-hamburger-dannosa#c000186) è possibile ricavare qualche informazione che potrebbe esser utile per chi volesse dire la sua.

Riassumo:
- l'icona burger è irriconoscibile ai più, è un dato di fatto. va integrata con una scritta "menu" che ne specifica la ragion d'essere
- il nodo gordiano è la presenza immediatamente visibile dei link principali almeno su desktop (es. tramite menu orizzontale). al momento nelle LG non è scritto che debbano esser obbligatoriamente presenti (burger o meno) anche se sono visibili nei siti pilota

I più critici invitano inoltre a considerare le ipotesi di:
- utilizzare la scritta menu sia su desktop che su mobile, ed eventualmente _in sostituzione dell'icona_
- utilizzare su desktop un "megamenu" visibile on hover (tap su touch) al posto del wardrobe laterale stile material design

Al momento le LG propongono un approccio di tipo "content first" che favorisca in sostanza la navigazione in-page. Ad esempio su funzionepubblica.gov.it i link del menu principale sono proposti in home in posizione preminente. Sui siti pilota delle PAC invece i link di primo livello portano a "home page di sezione".

Sarebbe interessante una discussione costruttiva in proposito.

Per quanto riguarda il menu che non funziona con javascript disabilitato, trattandosi di un dettaglio implementativo, posso segnalarlo ai fornitori che hanno lavorato ai diversi siti (e aggiungere che stiamo lavorando a un framework riutilizzabile in cui il problema non persiste).

**Comment by AlessandroVecchi** [comment]
L'icona "burger" (o in alternativa i 3 pallini) è diventata ormai uno standard molto diffuso dato il massiccio uso di dispositivi mobili ma a mio parere su desktop è sempre preferibile un menu in forma testuale (a questo proposito aprirò una segnalazione separata).

Premesso questo la mia domanda è un po' più terra terra: lo script usato per il menu è standardizzato o è solo una delle possibili scelte? Anche questo sarà incluso nei template che saranno distribuito (si spera) il mese di settembre?

**Comment by AlessandroVecchi** [comment]
Lo script del menu usato è basato su questo? http://takien.github.io/jPushMenu/

**Comment by gunzip** [comment]
non è standardizzato. su alcuni siti è stato utilizzato jPushMenu, su altri (es. design.italia.it o alpha.regione.sardegna.it) viene semplicemente assegata una classe al 'click' sul bottone.
sarà incluso nei template, con un'implementazione più attenta ai requisiti di accessibilità (es. https://frend.co/components/offcanvas/) e funzionante anche senza js :)

**Comment by sabas** [comment]
Mi pongo una domanda: su design.italia.it è usato il menu "visibile" che diventa burger quando scatta la media query ad una certa risoluzione, mentre su altri siti (il nuovo della RAS, Venezia)  il menu di default è già burger anche su desktop.
Quale sarebbe la best practice da seguire?

**Comment by AlessandroVecchi** [comment]
Beh design.italia.it non è un una demo ma elenca le linee guida, quindi le voci di menu non sono le stesse di un sito comunale.
Su http://design.italia.it/linee-guida/infoarchitettura/ ti spiega come deve essere costruito il menu.
Al menu burger, sempre visibile, si affiancano su schermi larghi le voci di menu sotto la testata. Anche io mi chiedo se abbia senso avere il burger sempre visibile invece di farlo apparire solo alla riduzione del viewport, come nel più classico dei design responsive. Forse il futuro è così.

@gunzip il progetto jPushMenu vedo che non ha aggiornamenti da 2 anni, a meno che abbia raggiunto lo stato dell'arte, personalmente non lo userei.

**Comment by AlessandroVecchi** [comment]
Nell'articolo su usabile.it si parla anche di un'altra questione che poi non è stata sviscerata qui: l'header che viene collassata allo scroll della pagina.
È una questione che mi sono posto subito anche io e la mia opinione è che fa molta scena ma la sua utilità è ben poca: ripetere il sito in cui sono è sostanzialmente inutile e non ha alcuna funzione legata all'usabilità o accessibilità, anzi comporta l'utilizzo di codice aggiuntivo e js. Per tornare al menu il classico pulsante "torna in alto" è più funzionale e ampiamente diffuso.
Tra l'altro sul comune di Biella notavo che c'è un problema quando viene aperto il menu dall'header collassata con firefox.

Aggiungo un suggerimento per le LG: la ripetizione (al momento non prevista) delle voci di menu principali anche nel footer. Anche questa una pratica che si è molto diffusa negli ultimi anni e che quindi credo sia ben assimilata dagli utenti.

**Comment by mariocariello** [comment]
Buongiorno a tutti, mi sono letto e riletto tutte le issue, consumato i polpastrelli nel digitare siti per eventuali soluzioni. Stiamo ristrutturando il sito www.reterurale.it, e personalmente ho trovato solo un sito che risolve le nostre problematiche.
Problema n°1: il nostro sito ha tante sotto sessioni (secondi livelli) con relativi terzi livelli. E' un portale da decine di migliaia di pagine.
Problema n°2: Il menu di primo livello stretto all'osso ha 7 voci e con circa 40 sotto livelli
Problema n°3: Il menu burger a nostro avviso non serve a nulla su risoluzioni desktop se non ad aumentare la navigazione di un click
Problema n°4: l'apertura dei menù on mouse open con abilitato sia il click sul padre che sui figli per noi è fondamentale
Senza tediarvi troppo ho visto che i colleghi nostri di ISMEA hanno realizzato con bootstrap/FlexCMP un buon compromesso a nostro parere.
Vi segnalo il link: http://www.ismea.it

**Comment by gunzip** [comment]
@mariocariello 

1-2. ok.

aggiungo che proprio durante le fasi di ristrutturazione è necessario validare l'architettura dell'informazione testandola con gli utenti, non lasciando la decisione ultima agli esperti di dominio (amministrativi, redazione, dirigenti) senza che vi sia un successivo riscontro (a volte aiuta a risparmiare qualche voce di menu oltre che qualche telefonata). inoltre alcune voci (es. contatti, amministrazione trasparente, ...) possono esser collocate nel footer ed eventualmente esser riproposte in evidenza sulla home.

3

stiamo effettuando dei testi di usabilità per valutare il modello. la versione definitiva di header e menu, oltre che esser l'argomento più controverso, è un elemento fondamentale per traghettare le LG verso una versione 'beta'. in base ai risultati le LG saranno riviste e/o integrate.

4

qualche considerazione.

- l'interazione mouse-over non esiste su mobile. tant'è che sul sito di ismea le tendine non compaiono su smartphone / tablet, ma si viene diretti direttamente alle pagine dei link di primo livello. lo stesso comportamento si ha navigando tramite tastiera (le voci di secondo menu non sono accessibili).

- in un menu orizzontale (es. mega-menu) il numero dei link è limitato dalla larghezza della viewport. il numero di voci che può contenere un menu ad albero verticale (es. quello accessibile tramite l'icon burger) è illimitato e si presta quindi meglio a contenere una "mappa del sito".

- l'utilizzo di un menu orizzontale è tecnicamente più complesso da implementare poiché deve prevedere una modalità di navigazione alternativa su mobile

- l'utilizzo di un menu a comparsa (es. mega menu stile mef.gov.it) dovrebbe soddisfare, tra gli altri, questo requisito: navigando tramite tastiera deve esser possibile utilizzare i livelli (navigazione ad albero); in caso contrario, per raggiungere l'ultima voce di un sotto-menu si è costretti a scorrere tutte le voci precedenti (con uno screen reader l'effetto è un'esperienza non ottimale). una buona implementazione che mi sento di consigliare poiché impiega i *necessari* attributi wai-aria, si trova qui: https://adobe-accessibility.github.io/Accessible-Mega-Menu/

per i suddetti motivi risulta spesso più pratico utilizzare delle homepage di sezione e/o dei menu contestuali (non globali).

le home di sezione hanno alcuni vantaggi rispetto ai mega menu:

- il numero di voci che è possibile inserire non è limitato da aspetti grafici (ne su desktop, ne su mobile)
- i link sono immediatamente visibili su mobile senza richiedere una o più interazioni (click su icona burger e/o click per espandere sottomenu)
- è possibile raggruppare i link in modo arbitrario, esporre eventualmente dei filtri di ricerca e abbinare ai link delle descrizioni
- sono tecnicamente facili da implementare e non necessitano di ulteriori attenzioni quali l'utilizzo corretto di wai-aria

questo è il pattern utilizzato, tra gli altri, su gov.uk, un sito complesso dove il menu globale consiste nei soli link di primo livello.

**Comment by mariocariello** [comment]
@gunzip 
Rieccomi a voi. Innanzitutto grazie x la celerità e la pazienza. 
Ecco in breve quello che è emerso parlando con i colleghi, con utenti utilizzatori del sito (regionali, addetti ai lavori, colleghi) dopo vari test/prove/colloqui:
Il burger menu è fuorviante su risoluzione desktop (da md in su)
Il burger menù quindi va bene solo per smartphone e piccoli dispositivi
Non è consigliato mettere molte voci/sottovoci nel burger menu esploso sennò non si riesce a navigare poichè x scorrere il menù si impazzisce. (x es. sul sito comune.venezia.it andateci con uno smartphone, cliccate sul burger poi andate su"per i cittadini" e poi su "presentare istanze, petizioni..." non a caso ho scelto la voce più in basso. Una volta cliccato il menù si chiude ma non si ricorda nè in che sezione di primo livello stavo nè tantomeno l'eventuale secondo/terzo livello.
In conclusione il burger menu va bene per il mobile ma se viene realizzato in versione "light" garantendo il supporto all'utente con almeno delle breadcrumb decenti.
Concordo sul fatto che un menù orizzontale è limitato dalla larghezza della viewport ma con la giusta dimensione del font e delle accortezze per non andare oltre le 8 voci con una parola forse una soluzione c'è.
Ad oggi l'unica soluzione che vedo per il nostro sito è quella di fare due menù distinti di navigazione.
Vi segnalo un'ultima cosa che più o meno è stata concordata da tutti gli attori coinvolti nel capire quale fosse la soluzione migliore:
Queste linee guida vanno bene per siti piccoli, con pochi contenuti e con una struttura navigazionale non troppo complessa. Su siti grandi, documentali, che sono una via di mezzo tra un quotidiano pieno di notizie, un repository pieno di documenti e banche dati con l'aggiunta di componenti web 2.0 tra cui oggetti infogr.am, padlet.com, widget vari etc. etc. ci troviamo stretti in una morsa che ci limita fortemente.
un saluto e buon lavoro a tutti

**Comment by gunzip** [comment]
ok le considerazioni sul burger. 8 voci sono tante (troppe ?)

puoi elaborare le considerazioni nella chiosa ? 

> ci  troviamo stretti in una morsa

**Comment by mariocariello** [comment]
"non lasciando la decisione ultima agli esperti di dominio (amministrativi, redazione, dirigenti)" cit.
