### ISSUE TITLE
Ottimizzare immagini sito LG

### ISSUE THREAD

**Issue by gunzip** [italia/designer.italia.it#189]
- [x] integrare PR #188 
- [x] lazy loading (es. http://callmecavs.com/layzr.js/, https://github.com/aFarkas/lazysizes)
- [x] tag per img responsive (https://github.com/mahnunchik/gulp-responsive)
- [ ] integrarla nel capitolo 'header' dopo merge modifiche

**Comment by sgelob** [comment]
Per il lazyload, consiglio di vedere anche questo repository https://github.com/aFarkas/lazysizes
