### ISSUE TITLE
Sostituire link a toolkit e codice negli esempi

### ISSUE THREAD

**Issue by gunzip** [italia/designer.italia.it#191]
Al raggiungimento della v1.0
secondo quanto visibile nella [roadmap](https://italia-it.github.io/ita-web-toolkit/docs/roadmap.html)
- [ ] Sostituire link "Scarica i componenti"
- [ ] Sostituire codice html negli esempi con riferimento (iframe) a pagine toolkit

**Comment by dgardina** [comment]
Buongiorno @gunzip,  pensi quindi che sia imminente il rilascio della v1.0?
Chiedo scusa, come ho già scritto in un altro post devo ammettere la mia non conoscenza di certi strumenti di cui ho letto nella documentazione del toolkit ma ti vorrei chiedere, non volendo/potendo programmare, come è possibile realizzare un template per un determinato CMS (nel mio caso, ad esempio, Joomla) seguendo le linee guida? Ho notato che, ad esempio, il Comune di Matera lo ha già fatto, nonostante le LG siano ancora in versione "alpha".. Grazie.

**Comment by gunzip** [comment]
non è imminente e le tempistiche dipenderanno anche (soprattutto ?) dalla partecipazione. questa è la roadmap: https://italia-it.github.io/ita-web-toolkit/docs/roadmap.html 

non volendo/potendo programmare, è impossibile realizzare un template per un determinato CMS. il consiglio è riutilizzare le soluzioni esistenti tenendo conto le le PA devono metterle a disposizione delle altre amministrazioni.
