### ISSUE TITLE
capitolo header: rivedere incipit

### ISSUE THREAD

**Issue by saiballo** [italia/designer.italia.it#192]
scusate ma forse mi sono perso: le specifiche per l'header delle amministrazioni centrali, dove sono finite?

qui trovo solo le locali:
http://design.italia.it/linee-guida/header/

**Comment by AlessandroVecchi** [comment]
L'instancabile Saibal!
Così a occhio credo che i siti delle amministrazioni centrali siano realizzati a stretto giro.

**Comment by saiballo** [comment]
non si molla! :-)

grazie

**Comment by gunzip** [comment]
@saiballo le indicazioni coincidono a meno delle peculiarità (es. infoarchitettura) descritte per le PAC. alcuni elementi (es. pulsante accedi ai servizi, impostazione del menu) sono in fase di test / definizione.

cfr. http://www.funzionepubblica.gov.it/ o http://bandaultralarga.italia.it/

**Comment by saiballo** [comment]
ok grazie ma non lo trovo affatto chiaro. riporto il paragrafo iniziale:

"Le indicazioni presenti in questa sezione vanno applicate nella progettazione di siti web per le amministrazioni locali (Regioni, Province, Comuni) e per enti e società a queste afferenti (siti tematici, società partecipate, consorzi, comunità, ...)."

quindi un neofita che arrivi per la prima volta su quella pagina si domanderà: "e per le amministrazioni centrali cambia qualcosa oppure no?"

personalmente riscriverei quel paragrafo mettendo in primo piano le specifiche per le PAC (che adesso non vengono neanche menzionate) e successivamente le diverse possibilità per le amministrazioni locali.

**Comment by gunzip** [comment]
direi che l'osservazione è corretta, la porto all'attenzione del gruppo di lavoro.

**Comment by saiballo** [comment]
grazie, buon lavoro
