### ISSUE TITLE
Grafica icone social

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/designer.italia.it#200]
Da un feedback interno è emerso che le icone di richiamo ai social network sono più efficaci se utilizzano il colore standard del social stesso.
Nel template sono state definite come standard delle icone con colore di sfondo generico e forma circolare. C'è un motivo specifico per questa scelta?
C'è libertà di operare diversamente?

**Comment by gunzip** [comment]
è possibile elaborare il processo di 'feedback interno' ? (ovvero esplicitare se è il risultato di test effettuati con gli utenti o scaturisce da supposizioni da parte degli amministratori o di chi sviluppa il sito). posso dire in merito che vengono utilizzate in tutti i siti pilota e non hanno mai costituito una criticità, ovvero le persone le hanno sempre riconosciute come sono. mi sento pertanto di consigliare di attenersi a quanto visibile nei template.

**Comment by AlessandroVecchi** [comment]
ho infatti precisato "interno" in quanto opinione di addetti ai lavori.
Siamo in attesa di feedback anche da tester esterni.
