### ISSUE TITLE
Ambiguità dei siti web design / designer ?

### ISSUE THREAD

**Issue by gunzip** [italia/designer.italia.it#40]
Attualmente esistono due siti paralleli (design.italia.it / designer.italia.it). L'idea era quella di avere un sito (designer.italia.it) in continuo aggiornamento (un deploy dopo ogni commit ? vedi #23) e un sito "ufficiale" (design.italia.it) in cui pubblicare release "stabili" in intervalli di tempo più ampi.

Sarebbe utile raccogliere un po' di opinioni a riguardo (serve ? è chiaro il funzionamento ? eventuali alternative / benchmark ? differenziamo i siti in qualche modo ?)

**Comment by fiaschi** [comment]
Credo che proprio per la natura di "ambiente di test" di designer.italia.it si possa optare tranquillamente per un deploy ogni commit, allo stesso tempo sarebbe utile differenziarlo, anche minimamente.

**Comment by webnicola** [comment]
Bisognerebbe evitare l'indicizzazione dell'ambiente di test, con un file robots.txt (http://www.robotstxt.org/robotstxt.html), aggiungendolo in .gitignore così da non bloccare quello ufficiale.

**Comment by gunzip** [comment]
@webnicola ok.

inoltre si potrebbe includere un "build number" e una data di aggiornamento nel footer di designer.*

**Comment by sabas** [comment]
Potete renderlo più chiaro ad esempio cambiando colore dell'header o mettendoci un ribbon bello grosso?
Poi per il build number sono d'accordo, potreste mettere un rXXXX e la data dopo "Versione alfa" nell'header

**Comment by didoo** [comment]
My 2 cent tips: usare due nomi simili genera sempre confusione. Perché non usare invece qualcosa come `dev.designer.italia.it` o `dev-designer.italia.it`, ma potrebbe essere essere `staging.designer.italia.it` oppure ancora `pre.designer.italia.it` o `build.designer.italia.it`
Insomma, qualsiasi cosa o nome che non sia confondibile con quello "vero".

**Comment by gunzip** [comment]
lo propongo

**Comment by ccontavalli** [comment]
Come persona che ha scoperto design.italia.it e designer.italia.it solo oggi, sono assolutamente d'accordo con @didoo. Non e` assolutamente intuitivo che "design" e` la versione ufficiale, mentre "designer" la versione in continuo aggiornamento.

Cambiare schema di colori o avere qualche altro segnale renderebbe piu` intuitivo, ma secondo me e` necessario cambiare il nome - aggiungere un "dev" da qualche parte. O utilizzare URL differenti.

**Comment by umbros** [comment]
Io terrei design.italia.it come sito principale dove saranno presenti le release e sposterei tutta la parte dev direttamente su github/github.io
